In [1]:
import pandas as pd

In [3]:
ls

 Volume in drive C is OS
 Volume Serial Number is A4B9-8E3D

 Directory of C:\Users\Sergi\OneDrive\Documents\GitHub\sergiguasch\projects

02/23/2022  05:48 PM    <DIR>          .
02/14/2022  11:30 AM    <DIR>          ..
02/23/2022  05:46 PM    <DIR>          .ipynb_checkpoints
02/23/2022  02:04 PM        42,801,241 case1_sell_out_etl_and_analysis.rar
02/14/2022  11:30 AM        45,580,638 data.csv
02/14/2022  11:30 AM    <DIR>          getafix
02/21/2022  03:31 PM    <DIR>          hangover
02/23/2022  05:48 PM             9,470 Untitled.ipynb
               3 File(s)     88,391,349 bytes
               5 Dir(s)  304,695,234,560 bytes free

In [5]:
pd.read_csv('alldata.csv')

,position,company,description,reviews,location
0,Development Director,ALS TDI,Development Director\r\nALS Therapy Developmen...,NaN,"Atlanta, GA 30301"
1,An Ostentatiously-Excitable Principal Research...,The Hexagon Lavish,"Job Description\r\n\r\n""The road that leads to...",NaN,"Atlanta, GA"
2,Data Scientist,Xpert Staffing,"Growing company located in the Atlanta, GA are...",NaN,"Atlanta, GA"
3,Data Analyst,Operation HOPE,DEPARTMENT: Program OperationsPOSITION LOCATIO...,44.0,"Atlanta, GA 30303"
4,Assistant Professor -TT - Signal Processing & ...,Emory University,DESCRIPTION\r\nThe Emory University Department...,550.0,"Atlanta, GA"
...,...,...,...,...,...
6959,Data Developer / Machine Learning Analyst,NetApp,Are you data-driven? We at NetApp believe in t...,574.0,"Sunnyvale, CA"
6960,Scientist I,"Pharmacyclics, an Abbvie Company",Pharmacyclics is committed to the development ...,26.0,"Sunnyvale, CA"
6961,Intern Scientist,Oath Inc,"Oath, a subsidiary of Verizon, is a values-led...",5.0,"Sunnyvale, CA"
6962,Senior Data & Applied Scientist,Microsoft,We are the Bing Core Relevance team responsibl...,4618.0,"Sunnyvale, CA"
6963,"Principal Data Scientist, Deep Learning",Comcast,Comcast’s Technology &amp; Product organizatio...,11610.0,"Sunnyvale, CA 94089"